POST http://127.0.0.1:8083/register
Content-Type: application/json

{
  "userId": "1",
  "user_name": "Vucuong1111111tnnd@gmail.com",
  "password": "123456",
  "full_name": "VuQuocCuong",
  "gender": "Nam",
  "phone_number": "0941587396",
  "birthday": "14-06-2012"
}

###
GET http://127.0.0.1:8083/login/Vucuong42tnnd@gmail.com/123456
Accept: application/json

###
GET http://127.0.0.1:8083/home
Accept: application/json


###
POST http://127.0.0.1:8083/home/flight
Content-Type: application/json

{
  "id_flight": "1",
  "image_flight": "image3",
  "title_flight": "title3",
  "date_flight": "12-04-2001"
}


###
POST http://127.0.0.1:8083/home/promotion
Content-Type: application/json

{
  "id_promotion": "1",
  "image_promotion": "image3"
}

###
POST http://127.0.0.1:8083/home/hotel
Content-Type: application/json

{
  "id_hotel": "1",
  "name_hotel": "name3",
  "image_hotel": "image3",
  "accommodationPolicies_hotel": "acc3",
  "description_hotel": "des3",
  "star_home": "4.7"
}

###
GET http://127.0.0.1:8083/home/detail/4
Accept: application/json

###
GET http://127.0.0.1:8084/home/room/4
Accept: application/json






