POST http://127.0.0.1:8086/register
Content-Type: application/json

{
  "user_name": "Vucuong11132tnnd@gmail.com",
  "password": "123456",
  "full_name": "VuQuocCuong",
  "gender": "Nam",
  "phone_number": "0941587396",
  "birthday": "14-06-2012"
}

###
GET http://127.0.0.1:8087/v1/home
Accept: application/json

###
POST http://127.0.0.1:8083/v1/home/hotel
Content-Type: application/json

{
  "id_hotel": "1",
  "name_hotel": "name3",
  "image_hotel": "image3",
  "accommodationPolicies_hotel": "acc3",
  "description_hotel": "des3",
  "star_home": "4.7",
  "id_city": "1"
}

###
GET http://127.0.0.1:8085/v1/home/hotel/detail/4
Accept: application/json

###
GET http://127.0.0.1:8086/v1/home/room/4
Accept: application/json

###
GET http://127.0.0.1:8085/v1/home/room/detail/5
Accept: application/json

###
GET http://127.0.0.1:8086/v1/home/city/hotel/1
Accept: application/json

###
POST http://127.0.0.1:8087/v1/home/hotel/booking
Content-Type: application/json

{
  "userId": "56",
  "roomId": "114",
  "checkin": " 2022-12-10",
  "checkout": "2022-12-11"
}




